.github/workflows/macos.yml
.github/workflows/release.yml
.github/workflows/ubuntu.yml
Makefile
README.adoc

#6 remove envsubst dependency

---

.github/workflows/release.yml

- metanorma/mn2pdf-ruby#1
@ronaldtse we need to add `secrets.PAT_TOKEN` as we did for other repos

metanorma/mn2pdf-ruby#1 Trigger mn2pdf-ruby

---

.github/workflows/test.yml

fontist installation

---

Makefile
README.adoc
pom.xml
src/main/java/org/metanorma/fop/PDFGenerator.java
src/main/java/org/metanorma/fop/SourceXMLDocument.java
src/main/java/org/metanorma/fop/Util.java

issue with path contains colon fixing, #120

---

src/main/java/org/apache/fop/render/pdf/PDFPainter.java
src/main/java/org/metanorma/fop/Util.java
src/main/resources/add_hidden_math.xsl

Hiddenmath update

---

src/main/resources/tables_only.xsl

Table autolayout child

---

src/main/java/org/metanorma/fop/fontConfig.java

updated for fontconfig checking, #142

---

src/main/java/org/metanorma/fop/eventlistener/LoggingEventListener.java

updated for #156

---

Makefile
README.adoc
pom.xml
src/main/java/org/apache/fop/events/EventFormatter.java
src/main/java/org/metanorma/fop/eventlistener/LoggingEventListener.java

Layout table

---

src/main/java/org/apache/fop/fonts/GlyphMapping.java
src/main/java/org/apache/fop/layoutmgr/inline/TextLayoutManager.java

Zerowidthspace

---

Makefile
README.adoc
pom.xml
src/main/java/org/metanorma/fop/Util.java
src/main/resources/tables_only.xsl
src/test/java/org/metanorma/fop/mn2pdfTests.java

Sourcecode highlight

---

.github/mscorefonts.yml
src/main/java/org/apache/fop/fonts/GlyphMapping.java
src/test/java/org/metanorma/fop/mn2pdfTests.java
src/test/resources/manifest.yml

GlyphMapping.java changed for issue, metanorma/metanorma-iso#878

---

Makefile
README.adoc
pom.xml
src/main/java/org/apache/fop/events/EventFormatter.java

add page number reading via parameter, fixing issue #163

---

src/main/java/org/metanorma/fop/PDFGenerator.java
src/main/java/org/metanorma/fop/SourceXMLDocument.java
src/main/java/org/metanorma/fop/XSLTconverter.java
src/main/resources/update_preprocess_xslt.xsl
src/test/java/org/metanorma/fop/SourceXMLDocumentTests.java
src/test/resources/a.presentation.xml

Preprocess xslt

---

Makefile
README.adoc
pom.xml
src/main/java/org/apache/fop/pdf/PDFStructElem.java

Pdf images plugin

---

Makefile
README.adoc
pom.xml
src/main/java/org/metanorma/fop/PDFGenerator.java

updated for metanorma/mnconvert#350

---

Makefile
README.adoc
pom.xml
src/main/resources/tables_only.xsl

update for table auto layout, metanorma/metanorma-iho#116

---

Makefile
README.adoc
pom.xml
src/main/resources/table_if.xsl

Table layout update

---

Makefile
README.adoc
pom.xml
src/main/java/org/apache/fop/fonts/Typeface.java
src/main/java/org/metanorma/fop/PDFGenerator.java
src/main/java/org/metanorma/fop/fontConfig.java
src/main/java/org/metanorma/fop/fonts/FOPFontAlternate.java
src/main/resources/pdf_fonts_config.xml

Font update

---

Makefile
README.adoc
pom.xml
src/main/java/net/sourceforge/jeuclid/fop/JEuclidElement.java
src/main/java/org/apache/fop/fo/XMLObj.java

jEuclid fix

---

Makefile
README.adoc
pom.xml
src/main/java/org/metanorma/fop/ifhandler/FOPIFFlatHandler.java

annotation processing fixed for metanorma/metanorma-ogc#517

---

Makefile
README.adoc
pom.xml
src/main/java/org/apache/fop/complexscripts/fonts/GlyphClassTable.java
src/main/java/org/apache/fop/fo/PropertyList.java
src/main/java/org/metanorma/fop/PDFGenerator.java
src/main/java/org/metanorma/fop/fontConfig.java

Fop config path

---

Makefile
README.adoc
pom.xml
src/main/java/org/metanorma/fop/fontConfig.java

Bad pfa font

---

README.adoc
src/main/java/org/metanorma/fop/fontConfig.java

Bad pfa font issue fix

---

Makefile
README.adoc
pom.xml
src/main/resources/tables_only.xsl

tables_only.xsl optimized for metanorma/mn-native-pdf-bsi#41

---

Makefile
README.adoc
pom.xml
src/main/resources/tables_only.xsl

tables_only.xsl updated for dl inside table, metanorma/metanorma-iec#248

---

src/main/java/org/metanorma/fop/PDFGenerator.java
src/main/java/org/metanorma/fop/fontConfig.java

fontist manifest file saving in debug mode, #212

---

src/main/java/org/metanorma/fop/PDFGenerator.java
src/main/java/org/metanorma/fop/Profiler.java
src/main/java/org/metanorma/fop/SourceXMLDocument.java
src/main/java/org/metanorma/fop/Util.java
src/main/java/org/metanorma/fop/ifhandler/FOPIFHiddenMathHandler.java

string width calculation added, #214

---

Makefile
README.adoc
pom.xml
src/main/java/org/apache/fop/render/pdf/PDFStructureTreeBuilder.java
src/main/resources/pdf_fonts_config.xml

Tags tree update

---

src/main/java/org/metanorma/fop/PDFGenerator.java
src/main/java/org/metanorma/fop/SourceXMLDocument.java
src/main/java/org/metanorma/fop/Util.java
src/main/java/org/metanorma/fop/ifhandler/FOPXMLPresentationHandler.java

memory consumption updated, #214

---

Makefile
README.adoc
pom.xml
src/main/java/org/metanorma/fop/PDFGenerator.java

updated for #214

---

Makefile
README.adoc
pom.xml
src/main/java/org/metanorma/fop/SourceXMLDocument.java
src/main/java/org/metanorma/fop/fontConfig.java
src/test/java/org/metanorma/fop/mn2pdfTests.java

Update for SVG fonts

---

Makefile
README.adoc
pom.xml
src/main/java/org/metanorma/fop/fontConfig.java

fixed issue with missing fonts, #177

---

src/main/java/org/metanorma/fop/SourceXMLDocument.java

fonts extraction from font-family issue fixed, #177

---

Makefile
README.adoc
pom.xml
src/main/java/org/metanorma/fop/PDFGenerator.java
src/main/java/org/metanorma/fop/mn2pdf.java
src/main/resources/xfdf_simple.xsl

review formatting updated, metanorma/metanorma-standoc#842

---

Makefile
README.adoc
pom.xml
src/main/resources/table_if.xsl

Update table width

---

Makefile
README.adoc
pom.xml
src/main/java/org/metanorma/fop/PDFGenerator.java

updated for attachments support, metanorma/metanorma-standoc#872

---

Makefile
README.adoc
pom.xml
src/main/java/org/metanorma/fop/PDFGenerator.java
src/main/java/org/metanorma/fop/SourceXMLDocument.java
src/test/java/org/metanorma/fop/SourceXMLDocumentTests.java

table width algorithm performance optimization, #245

---

Makefile
README.adoc
pom.xml
src/main/java/org/metanorma/fop/annotations/PDFTextAnnotationStripper.java
src/main/java/org/metanorma/fop/ifhandler/FOPIFIndexHandler.java

fixing issue #255

---

Makefile
README.adoc
pom.xml
src/main/java/org/metanorma/fop/PDFGenerator.java

table cell count threshold decreased, metanorma/mn-native-pdf#709

---

Makefile
README.adoc
pom.xml
src/main/java/org/metanorma/fop/PDFGenerator.java

fixing issue metanorma/metanorma-plateau#48

---

Makefile
README.adoc
pom.xml
src/main/java/org/metanorma/fop/annotations/Annotation.java

fix missing hyperlinks issue, #259

---

Makefile
README.adoc
pom.xml
src/main/java/org/apache/fop/fo/Constants.java
src/main/java/org/apache/fop/fo/FOPropertyMapping.java
src/main/java/org/apache/fop/fo/FOText.java
src/main/java/org/apache/fop/fo/extensions/ExtensionElementMapping.java
src/main/java/org/apache/fop/fo/flow/Block.java
src/main/java/org/apache/fop/fo/flow/BlockContainer.java
src/main/java/org/apache/fop/fo/flow/InlineLevel.java
src/main/java/org/apache/fop/fo/properties/CommonFont.java
src/main/java/org/apache/fop/fo/properties/LengthRangeProperty.java
src/main/java/org/apache/fop/fo/properties/SpaceProperty.java
src/main/java/org/apache/fop/layoutmgr/BlockContainerLayoutManager.java
src/main/java/org/metanorma/Constants.java
src/main/java/org/metanorma/fop/PDFGenerator.java

Shrink to fit

---

src/main/java/org/apache/fop/fonts/MultiByteFont.java

patch from FOP-2529 applied, metanorma/mn-samples-plateau#168

---

Makefile
README.adoc
pom.xml
src/main/java/org/apache/fop/pdf/PDFFileSpec.java
src/main/java/org/apache/fop/render/pdf/PDFRenderingUtil.java
src/main/java/org/apache/fop/render/pdf/extensions/PDFEmbeddedFileAttachment.java
src/main/java/org/apache/fop/render/pdf/extensions/PDFEmbeddedFileElement.java
src/test/resources/iso.international-standard.xsl

volatile flag added for attachments, #299

---

Makefile
README.adoc
pom.xml
src/main/java/org/apache/fop/render/pdf/extensions/PDFEmbeddedFileAttachment.java
src/main/java/org/apache/fop/render/pdf/extensions/PDFExtensionHandler.java
src/test/resources/iso.international-standard.xsl

updated for fixing IF for attachments, #267

---

Makefile
README.adoc
pom.xml
src/main/java/org/metanorma/fop/PDFGenerator.java

PDF A mode disabling added, metanorma/metanorma-plateau#121

---

Makefile
README.adoc
pom.xml
src/main/java/org/apache/fop/complexscripts/util/JapaneseToNumbers.java
src/main/java/org/apache/fop/complexscripts/util/NumberConverter.java
src/test/java/org/metanorma/fop/mn2pdfTests.java

page numbers in Japanese format identifier fixed, #304

---

Makefile
README.adoc
pom.xml
src/main/java/org/apache/fop/apps/FopConfParser.java
src/main/java/org/apache/fop/events/EventFormatter.java
src/main/java/org/apache/fop/layoutmgr/BlockContainerLayoutManager.java
src/main/java/org/apache/fop/layoutmgr/BlockStackingLayoutManager.java
src/main/java/org/apache/fop/layoutmgr/FlowLayoutManager.java
src/main/java/org/apache/fop/layoutmgr/LayoutContext.java
src/main/java/org/apache/fop/layoutmgr/StaticContentLayoutManager.java
src/main/java/org/apache/fop/layoutmgr/inline/InlineContainerLayoutManager.java
src/main/java/org/apache/fop/layoutmgr/inline/LineLayoutManager.java
src/main/java/org/apache/fop/layoutmgr/inline/TextLayoutManager.java
src/main/java/org/apache/fop/pdf/PDFStructElem.java
src/main/java/org/apache/fop/render/intermediate/IFParser.java
src/main/java/org/apache/fop/render/intermediate/extensions/DocumentNavigationHandler.java
src/main/java/org/apache/fop/render/pdf/PDFRenderingUtil.java
src/main/java/org/apache/fop/svg/font/FOPGVTGlyphVector.java

updated for Apache FOP 2.10, #301

---

src/main/java/org/apache/fop/render/pdf/pdfbox/FOPPDFMultiByteFont.java
src/main/java/org/apache/fop/render/pdf/pdfbox/FontContainer.java
src/main/java/org/apache/fop/render/pdf/pdfbox/ImageConverterPDF2G2D.java
src/main/java/org/apache/fop/render/pdf/pdfbox/MergeCFFFonts.java
src/main/java/org/apache/fop/render/pdf/pdfbox/PDFBoxAdapterUtil.java
src/main/java/org/apache/fop/render/pdf/pdfbox/PDFCloner.java
src/main/java/org/apache/fop/render/pdf/pdfbox/PDFWriter.java
src/main/java/org/apache/fop/render/pdf/pdfbox/PSPDFGraphics2D.java
src/main/java/org/apache/fop/render/pdf/pdfbox/PageParentTreeFinder.java
src/main/java/org/apache/fop/render/pdf/pdfbox/PreloaderPDF.java
src/main/java/org/apache/fop/render/pdf/pdfbox/StructureTreeMerger.java
src/main/java/org/apache/fop/render/pdf/pdfbox/StructureTreeMergerUtil.java

added classes from FOP PDF Images plugin to support PDFBox 3.0.3, #317

---

Makefile
README.adoc
pom.xml
src/main/java/org/metanorma/fop/ifhandler/FOPXMLPresentationHandler.java

semantic element added for removing, metanorma/iso-2533#40

---

Makefile
README.adoc
pom.xml
src/main/java/org/apache/fop/fo/flow/BlockContainer.java
src/main/java/org/metanorma/fop/PDFGenerator.java
src/main/java/org/metanorma/fop/tags/TableCaption.java

Table tags

---

Makefile
README.adoc
pom.xml
src/main/resources/META-INF/MANIFEST.MF

jEuclid font for double struck added, metanorma/metanorma-iso#1323

---

Makefile
README.adoc
pom.xml
src/main/java/org/apache/fop/render/intermediate/extensions/DocumentNavigationHandler.java
src/main/resources/META-INF/MANIFEST.MF

wrong page reference for named destination fix, #334

---

Makefile
README.adoc
pom.xml
src/main/java/org/metanorma/fop/utils/ImageData.java
src/main/resources/META-INF/MANIFEST.MF

EXIF metadata reading added, metanorma/metanorma-ieee#490

---

Makefile
README.adoc
pom.xml
src/main/java/org/metanorma/fop/PDFGenerator.java
src/main/java/org/metanorma/fop/mn2pdf.java
src/main/resources/META-INF/MANIFEST.MF

Added XSLT override command line parameter

---

Makefile
README.adoc
pom.xml
src/main/resources/META-INF/MANIFEST.MF
src/main/resources/tables_only.xsl

Table autolayout optimize

---

Makefile
README.adoc
pom.xml
src/main/java/org/metanorma/fop/SourceXMLDocument.java
src/main/resources/META-INF/MANIFEST.MF
src/main/resources/xfdf_simple.xsl

review renamed to annotation, metanorma/metanorma-standoc#1053
